models/base.py
class Base():
    """
    Base Model is for serialization
    """

    def __init__(self, *args, **kwargs):
        from uuid import uuid4
        for (k, v) in kwargs.items():
            setattr(self, k, v)
        if not 'id' in kwargs.items():
            self.id = str(uuid4())

    def to_dict(self):
        """
        Turn the object into a dictionary
        """
        return self.__dict__

models/user.py
from models.base import Base


class ProfileInformation(Base):
    """ public information about a given entity """
    def __init__(self, *args, **kwargs):
        """ init """
        super().__init__(*args, **kwargs)
        self.community_interests = []
        self.values = []
        self.project_interests = []
        self.big_why = ''


class User(Base):
    """
    Customer information
    """
    def __init__(self, *args, **kwargs):
        """ init """
        super().__init__(*args, **kwargs)
        profileInfo = ProfileInformation()
        self.email = kwargs.get('email')
        self.username = kwargs.get('username')
        self.handle = kwargs.get('handle')
        self.password = kwargs.get('password')
        self.collectives = []
        self.roles = []
        self.invitations_into_collectives = []
        self.my_requests_to_join_collectives = []
        self.notifications = []
        self.profile_info = profileInfo.id

api/__init__.py
from api.v1 import *
from api.v1.users import *

api/v1/__init__.py
from flask import Blueprint

api_v1 = Blueprint("api", __name__, url_prefix="/api")

main.py
"""
-----------------------------
  The Point Is to Change It | Entry Point
-----------------------------

Entry Point Contains:
1. bluprint registrations
2. authenticate request
3. error handling
4. global helper functions

"""

from flask import Flask, jsonify, render_template
from flask_cors import (CORS, cross_origin)
from uuid import uuid4
from os import environ
from api import *
from routes import *


# initiate flask app and secret key
app = Flask(__name__)
if "FLASK_SECRET_KEY" in environ:
    app.secret_key = environ["FLASK_SECRET_KEY"]
else:
    environ["FLASK_SECRET_KEY"] = str(uuid4())

# cors protection
CORS(app, resources={r"*": {"origins": "*"}})

# register blueprints
app.register_blueprint(api_v1)
app.register_blueprint(docs_v1)





@app.before_request
def before():
    """
    authenticate request before routes
    """
    pass

@app.errorhandler(400)
def bad_request(error) -> str:
    """
    Request is bad
    """
    return jsonify({"error": "Bad Request, https required"}), 400


@app.errorhandler(404)
def not_found(error) -> str:
    """
    Not found handler
    """
    return jsonify({"error": "Not found"}), 404


@app.errorhandler(403)
def Forbidden(error) -> str:
    """
    Forbidden handler
    """
    return jsonify({"error": "Forbidden"}), 403


@app.errorhandler(401)
def Unauthorized(error) -> str:
    """
    Unauthorized handler
    """
    return jsonify({"error": "Unauthorized"}), 401


if __name__ == '__main__':
    # This is used when running locally only. When deploying to Google App
    # Engine, a webserver process such as Gunicorn will serve the app. This
    # can be configured by adding an `entrypoint` to app.yaml.
    app.run(host='127.0.0.1', port=8080, debug=True)
# [END gae_python38_app]

routes/__init__.py
from routes.docs import docs_v1

routes/docs/__init__.py
from flask import Blueprint, render_template

docs_v1 = Blueprint("docs", __name__, url_prefix="/docs")

@docs_v1.route('/', methods=['GET'], strict_slashes=False)
def index():
    return render_template('/docs/index.html')

@docs_v1.route('/stories', methods=['GET'], strict_slashes=False)
def stories():
    return render_template('/docs/stories.html')

templates/base.html
<!doctype html>

<html lang="en" class="bg-dark">
<head>
  <meta charset="utf-8">

  {% block head %}
  <title>{% block title %}{% endblock %} The Point Is to Change It</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">
  <link rel="stylesheet" href="{{ url_for('static', filename='base.css') }}">
  {% endblock %}


</head>

<body>
  <header>

    
  </header>

  <main>


  {% block content %}
  {% endblock %}
  </main>

  <footer>
    {% block footer %}
      &copy; Copyright 2020 <a class="text-white" href="http://github.com/rmolimock">Russell Molimock</a>, all rights reserved
    {% endblock %}
  </footer>

</body>
</html>

templates/docs/index.html
{% extends 'base.html' %}
{% block title %}Docs | {% endblock %}
{% block head %}
  {{ super() }}    
  <link rel="stylesheet" href="{{ url_for('static', filename='docs/docs.css') }}">
{% endblock %}


  {% block content %}

  <header>
      <h1>The Point Is to Change It Documentation</h1>
  </header>


  <section id="docs-index">
    <ul>
      <h2>Index</h2>
        <li><a href="{{ url_for('docs.stories')}}">Stories</a></li>
        <li><a href="#directory-tree">Directory Tree</a></li>
        <li><a href="#routes">Routes</a></li>
        <li><a href="#api-enpoints">API Endpoints</a></li>
        <li><a href="#models">Models</a></li>
    </ul>
  </section>



  <section id="directory-tree">
    <ul>
      <h2>Directory Tree</h2>
      <li></li>
    </ul>
  </section>

  <section id="routes">
    <ul>
      <h2>Routes</h2>

      <li id="route-0">
        <h3 class="todo">1 Status: To Do</h3>
        <h3>GET /</h2>
        <ol>
          <h3>Acceptance Criteria</h3>
          <li>Return a static template with information about The Point Is to Change It, focused on driving visitors to <a href="#route-1">route #1</a></li>
        </ol>
      </li>

      <li id="route-1">
        <h3 class="todo">1 Status: To Do</h3>
        <h3>GET /register</h2>
        <ol>
          <h3>Acceptance Criteria</h3>
          <li>Return a template with user a registration form, as per <a href="{{ url_for('docs.stories') }}#story-1">user story #1</a></li>
          <li>Registration form has action set to route POST /register</li>
        </ol>
      </li>

      <li id="route-2">
        <h3 class="todo">2 Status: To Do</h3>
        <h3>POST /register</h2>
        <ol>
          <h3>Acceptance Criteria</h3>
          <li>Calls /api/register to review and save user credentials</li>
          <li>If registration is successful, redirect to user's profile at <a href="#route-3">route #3</a></li>
          <li>Otherwise, redirect to the landing page at route 0</li>
        </ol>
      </li>

      <li id="route-1">
        <h3 class="todo">1 Status: To Do</h3>
        <h3>POST /register</h2>
        <ol>
          <h3>Acceptance Criteria</h3>
          <li>Calls /api/register to review and save user credentials</li>
          <li>if registration is successful, redirect to user's profile at <a href="#route-2">route #2</a></li>
        </ol>
      </li>

    </ul>
  </section>

  <section id="api-enpoints">
    <ul>
      <h2>API Endpoints</h2>
      <li></li>
    </ul>
  </section>

  <section id="models">
    <ul>
      <h2>Models</h2>
      <li></li>
    </ul>
  </section>
  


  {% endblock %}

templates/docs/stories.html
{% extends 'base.html' %}
{% block title %}Docs | {% endblock %}
{% block head %}
  {{ super() }}    
  <link rel="stylesheet" href="{{ url_for('static', filename='docs/docs.css') }}">
{% endblock %}


  {% block content %}

  <header>
      <h1>The Point Is to Change It Documentation</h1>
  </header>

  <section id="docs-index">
    <ul>
      <h2>Index</h2>
        <li><a href="{{ url_for('docs.stories')}}">Stories</a></li>
        <li><a href="{{ url_for('docs.index') }}">Directory Tree</a></li>
        <li><a href="{{ url_for('docs.index') }}">Routes</a></li>
        <li><a href="{{ url_for('docs.index') }}">API Endpoints</a></li>
        <li><a href="{{ url_for('docs.index') }}#models">Models</a></li>
    </ul>
  </section>

<section id="stories">
<ul>

    <h1>Stories</h1>

    <li id="story-0">
    <h3 class="todo">0 Status: To Do</h3>
    <h2>As a visitor, I want to learn more about The Point Is to Change It, so I can understand it's value.</h2>
    <ul>
        <h3>Acceptance Criteria</h3>
        <li></li>
    </ul>
    </li>

    <li id="story-1">
    <h3 class="todo">1 Status: To Do</h3>
    <h2>As a visitor, I want to register, so I can log into my account.</h2>
    <ol>
        <h3>Acceptance Criteria</h3>
        <li>Inputs for 5 fields: username, handle, email, password, and password confirmation</li>
        <li>Password must be > 7 characters, contain one uppercase charater, and one special character</li>
        <li>Failure to meet password criteria alerts the user to the error</li>
        <li>Email must be unique</li>
        <li>Handle must be unique</li>
        <li>All fields are required</li>
        <li>Successful registration redirects to an account page where more information is requested</li>
    </ol>
    </li>

    <li id="story-2">
    <h3 class="todo">2 Status: To Do</h3>
    <h2>As a user, I want to complete my profile information, so I can connect with others more easily.</h2>
    <ul>
        <h3>Acceptance Criteria</h3>
        <ol>
        <li>User can choose from a selection of at least several avatars to represent them</li>
        <li>User can answer any or all of their profile prompts (text inputs):</li>
        <ol>
            <li>What is your Big Why?</li>
            <li>What kind of communities are you looking for?</li>
            <li>What are your values?</li>
            <li>What are your interests?</li>
        </ol>
        <li>After modifying the above, user can save their new profile information</li>
        <li>User is alerted that changes have been saved</li>
        <li>Text fields do not accept code and will display an error if any is present</li>
        </ol>
    </ul>
    </li>

</ul>
</section>

{% endblock %}